# Generated by Django 6.1 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['exam', 'order']},
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.CharField(choices=[('A', 'Exam A'), ('B', 'Exam B'), ('C', 'Exam C'), ('D', 'Exam D')], default='A', max_length=1),
        ),
    ]
