# Generated by Django 6.1 on 2026-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
