# Generated by Django 6.1 on 2026-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.CharField(choices=[('A', 'Exam A'), ('B', 'Exam B'), ('C', 'Exam C'), ('D', 'Exam D'), ('E', 'Exam A – Appendix')], default='A', max_length=1),
        ),
    ]
