# Generated by Django 6.1 on 2026-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['certification', 'exam', 'order']},
        ),
        migrations.AddField(
            model_name='question',
            name='certification',
            field=models.CharField(default='ctfl', max_length=20),
        ),
    ]
